### ISSUE TITLE
Quick retry speeds up beatmap at beginning

### ISSUE THREAD

**Issue by Sowlokt** [McKay42/McOsu#263] opened 2020-02-26 02:09 UTC
So on a few beatmaps, when the quick retry button is pressed and the beatmap restarts, the beginning speeds up really quick for around 0.2s, as to catch up to the starting notes.

My guess is that, as the quick retry, in McOsu, tries at all time to skip the introduction of the music in any beatmap, it overdoes it on the beatmap that start on the first note. So it doesn't compensate correctly for that and misfires the skip somehow.

For example, the problem appears on the beatmap : https://osu.ppy.sh/beatmapsets/492407#osu/1049018

**Comment by McKay42** [comment] 2020-02-26 10:58
> 
> 
> So on a few beatmaps, when the quick retry button is pressed and the beatmap restarts, the beginning speeds up really quick for around 0.2s, as to catch up to the starting notes.
> 
> My guess is that, as the quick retry, in McOsu, tries at all time to skip the introduction of the music in any beatmap, it overdoes it on the beatmap that start on the first note. So it doesn't compensate correctly for that and misfires the skip somehow.

Ah no, this is a sideeffect of the new initial audio play time interpolation I added to fix stuttering at the beginning for some sound cards/drivers (they erroneously report playback position 0 for like half a second while the music has already started playing, so the game has to simulate virtual playback time for a certain duration at the start of tracks).

I can reproduce it thank you, will be fixed with the next build.

**Comment by McKay42** [comment] 2020-02-29 20:50
Should be fixed in version 31.05, please validate.

**Comment by Sowlokt** [comment] 2020-03-01 01:10
Fixed for me in 31.05, latest build released through Steam.

**Comment by Sowlokt** [comment] 2020-03-08 04:18
Bug reappeared in 31.06 (Steam).

Test case : https://osu.ppy.sh/beatmapsets/396994#osu/1067358

**Comment by McKay42** [comment] 2020-03-08 13:09
Should now definitely be fixed in version 31.07, after https://github.com/McKay42/McEngine/commit/bc5c93ae36a90efcdff217125fbe44f3bf56967a

**Comment by Sowlokt** [comment] 2020-03-08 15:42
Fixed for me in 31.07 (Steam)

Tested : 
https://osu.ppy.sh/beatmapsets/396994#osu/1067358
https://osu.ppy.sh/beatmapsets/492407#osu/1049018

Thank you for reactivity McKay!

**Comment by NixXSkate** [comment] 2020-03-11 03:16
The effect seems to be more mild, but seems to be happening more consistently often on 31.07

**Comment by Sowlokt** [comment] 2020-03-11 09:03
Do you have maps that this is happening on that I can test on my side to reproduce the issue ?

**Comment by McKay42** [comment] 2020-03-12 10:42
I'm pretty sure this is the same as https://github.com/ppy/osu-framework/pull/3354/

So enabling [BASS_CONFIG_DEV_NONSTOP](https://www.un4seen.com/doc/#bass/BASS_CONFIG_DEV_NONSTOP.html) with the next build should hopefully fix it.
Everything else should be covered by the existing interpolation method.

**Comment by McKay42** [comment] 2020-03-17 11:13
Hopefully fixed™ in version 31.08.

**Comment by McKay42** [comment] 2020-03-24 16:37
Any updates on this?

**Comment by Sowlokt** [comment] 2020-03-25 17:01
Was fine for me on 31.07.
Need an update from @NixXSkate .

**Comment by McKay42** [comment] 2020-03-29 14:21
Closing for now.

**Closed by McKay42** 2020-03-29 14:21 UTC
