### ISSUE TITLE
When holding a key somehow McOsu try to mke that holding pressing so fast and it will do that after you not hold a key anymore

### ISSUE THREAD

**Issue by dumb-stuff** [McKay42/McOsu#315] opened 2021-06-04 03:21 UTC

**Comment by McKay42** [comment] 2021-06-04 08:47
I don't understand what you mean, can you write step-by-step instructions on how to reproduce this?

**Comment by dumb-stuff** [comment] 2021-06-05 10:45
1. install mcosu from steam
2.Enter random map
3.hold your key that bind to click circles
4. See your result at key overlay

**Comment by McKay42** [comment] 2021-06-06 17:20
Which keys do you have bound for k1/k2?

**Comment by dumb-stuff** [comment] 2021-06-07 03:43
> Which keys do you have bound for k1/k2?

A/S

**Comment by McKay42** [comment] 2021-06-07 09:27
I can't reproduce this. Please record a video of it happening.

**Comment by dumb-stuff** [comment] 2021-06-08 04:46
> I can't reproduce this. Please record a video of it happening.

Okay

**Comment by dumb-stuff** [comment] 2021-06-14 09:58
@McKay42 
https://streamable.com/bckc90

**Comment by McKay42** [comment] 2021-06-14 10:14
> https://streamable.com/bckc90

Your recording is broken, freezes after 2 seconds, try again.

**Comment by dumb-stuff** [comment] 2021-06-14 10:17
@McKay42 here https://streamable.com/qan9f3 try this

**Comment by dumb-stuff** [comment] 2021-06-14 10:18
My obs is overload so it lags
my bad

**Comment by McKay42** [comment] 2021-06-14 10:25
> 
> 
> My obs is overload so it lags
> my bad

I can't see anything useful there because the recording is so extremely laggy.
How many fps do you get during regular playing?

**Comment by dumb-stuff** [comment] 2021-06-15 13:53
> > My obs is overload so it lags
> > my bad
> 
> I can't see anything useful there because the recording is so extremely laggy.
> How many fps do you get during regular playing?

200 +

**Comment by McKay42** [comment] 2021-07-30 08:44
Any update on this? If not then I'll close it next time I come here.

**Closed** 2021-08-02 10:15 UTC
