### ISSUE TITLE
BPM HUD gets stuck on highest BPM

### ISSUE THREAD

**Issue by SneakyLeif1020** [McKay42/McOsu#237] opened 2019-04-15 21:09 UTC
It seems like it shows the correct BPM until the first note. After that, the HUD automatically changes to the highest BPM in the map.

**Comment by McKay42** [comment] 2019-04-22 10:48
Is caused by having any speed multiplier != 1.0 and slow music loads and lead-in time, since the BPM is multiplied by the speed value set on the audio track (which only returns the correct value after it has been started/loaded, else it defaults to 1.0).

Fix will be in the next update.

**Comment by McKay42** [comment] 2019-05-26 16:06
Fixed in 29.5

**Closed by McKay42** 2019-05-26 16:06 UTC
