### ISSUE TITLE
Maps start inconsistently

### ISSUE THREAD

**Issue by NixXSkate** [McKay42/McOsu#267] opened 2020-03-08 04:02 UTC
Sometimes when starting a map, a random part of the song will play for half a second, then cut out, then the incoming note will appear to have a very slow AR and SV until catching up to the proper settings. Started happening about 3 patches ago I believe?

**Comment by McKay42** [comment] 2020-03-08 12:04
Duplicate of #263

**Closed by McKay42** 2020-03-08 12:04 UTC
